name: 🚀 Feature Request
description: Suggest a new feature or enhancement for Aditi
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide detailed information about your proposal.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify you've completed these steps
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked the roadmap and known limitations
          required: true
        - label: This is not a bug report (use bug report template instead)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: "Describe the problem or limitation you're experiencing"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: "Describe your ideal solution in detail"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - CLI Commands & Interface
        - Rule Processing & Analysis
        - Auto-fixing & Transformations
        - Configuration & Setup
        - Performance & Optimization
        - Documentation & Examples
        - Container & Dependencies
        - Reporting & Output
        - Integration (CI/CD, Git, etc.)
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to your workflow?
      options:
        - High - Blocking my current work
        - Medium - Would significantly improve my workflow
        - Low - Nice to have enhancement
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        Example scenarios:
        1. When working with large repositories...
        2. In CI/CD pipelines...
        3. For specific document types...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions or workarounds have you considered?
      placeholder: "Describe alternative approaches or current workarounds you use"

  - type: textarea
    id: examples
    attributes:
      label: Example Implementation
      description: If you have ideas about how this could work, share them
      placeholder: |
        Command examples:
        ```bash
        aditi check --output-format json
        aditi fix --custom-rule my-rule.yml
        ```
      render: bash

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to submit a PR for this feature
        - label: I can help with testing the implementation
        - label: I can provide additional use cases or feedback
        - label: I prefer to wait for maintainer implementation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that would help understand this feature request
      placeholder: "Screenshots, mockups, related tools, inspiration sources, etc."