# Jekyll configuration for GitHub Pages
title: Aditi - AsciiDoc DITA Integration
description: A CLI tool to prepare AsciiDoc files for migration to DITA
author: Rolfe DH
email: your-email@example.com
baseurl: "/aditi" # the subpath of your site, e.g. /blog
url: "https://rolfedh.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  design:
    output: true
    permalink: /design/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Rolfe DH"
  - scope:
      path: ""
      type: "design"
    values:
      layout: "page"

# Navigation
header_pages:
  - design.md
  - about.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/